// Generated by CoffeeScript 1.6.2
(function() {
  describe("App namespace", function() {
    return it("should be defined", function() {
      return expect(Happify).toBeDefined();
    });
  });

}).call(this);
